import { createApp, reactive } from "vue";
import App from "./App.vue";
import './style.css'
import VCalendar from "@peeraop21/v-calendar-buddhist";
import "@peeraop21/v-calendar-buddhist/style.css";

const app = createApp(App);

app.config.devtools = true;

app.use(VCalendar, {
  locale: "th-TH",
  firstDayOfWeek: 1,
});

const translations = {
  th: {
    'Demo / Simulate Mode': 'โหมดจำลอง',
    'Simulate Mode': 'โหมดจำลอง',
    'ON': 'เปิด',
    'OFF': 'ปิด',
    'Run Random All': 'สุ่มทั้งหมด',
    'Stop Random': 'หยุดสุ่ม',
    'Value': 'ค่า',
    'No devices found.': 'ไม่พบอุปกรณ์',
    'Dashboard': 'แดชบอร์ด',
    'Setting': 'ตั้งค่า',
    'Demo': 'จำลอง',
    'Alarm History': 'ประวัติแจ้งเตือน',
    'Interaction': 'ควบคุม',
    'Edit Mode': 'โหมดแก้ไข',
    'Exit Edit': 'ออกจากโหมดแก้ไข',
    'Add Card': 'เพิ่มการ์ด',
    'All Rooms': 'ทุกห้อง',
    'All Device Types': 'ทุกประเภทอุปกรณ์',
    'System Settings': 'การตั้งค่าระบบ',
    'Manage PLC system settings': 'จัดการการตั้งค่าระบบ PLC Monitoring',
    'Type Setting': 'ตั้งค่าประเภทอุปกรณ์',
    'Add Type': 'เพิ่มประเภท',
    'Device Type': 'ประเภทอุปกรณ์',
    'Actions': 'จัดการ',
    'No Device Types found.': 'ไม่พบประเภทอุปกรณ์',
    'Edit Device Type': 'แก้ไขประเภทอุปกรณ์',
    'Add Device Type': 'เพิ่มประเภทอุปกรณ์',
    'Name': 'ชื่อ',
    'Description': 'คำอธิบาย',
    'Display Types': 'ประเภทการแสดงผล',
    'Cancel': 'ยกเลิก',
    'Update': 'อัปเดต',
    'Create': 'สร้าง',
    'Edit': 'แก้ไข',
    'Delete': 'ลบ',
    'Save': 'บันทึก',
    'Close': 'ปิด',
    'Search': 'ค้นหา',
    'Add': 'เพิ่ม',
    'Add Device': 'เพิ่มอุปกรณ์',
    'Edit Device': 'แก้ไขอุปกรณ์',
    'Address': 'ที่อยู่',
    'Label': 'ป้ายชื่อ',
    'Room': 'ห้อง',
    'Type': 'ประเภท',
    'Data Type': 'ประเภทข้อมูล',
    'Min': 'ค่าต่ำสุด',
    'Max': 'ค่าสูงสุด',
    'Unit': 'หน่วย',
    'Alert': 'แจ้งเตือน',
    'Alert Low': 'แจ้งเตือนต่ำ',
    'Alert High': 'แจ้งเตือนสูง',
    'No devices.': 'ไม่มีอุปกรณ์',
    'Working Time': 'ช่วงเวลาทำงาน',
    'Start Time': 'เวลาเริ่มต้น',
    'End Time': 'เวลาสิ้นสุด',
    'PLC Debug': 'PLC Debug',
    'Room Setting': 'ตั้งค่าห้อง',
    'Add Room': 'เพิ่มห้อง',
    'Edit Room': 'แก้ไขห้อง',
    'No rooms found.': 'ไม่พบห้อง',
    'Device': 'อุปกรณ์',
    'Showing': 'แสดง',
    'of': 'จาก',
    'entries': 'รายการ',
    'Show': 'แสดง',
    'Device Type': 'ประเภทอุปกรณ์',
    'Type': 'ประเภท',
    'Work today': 'ทำงานวันนี้',
    'Working Hours': 'ช่วงเวลาทำงาน',
    'Add Shift': 'เพิ่มกะ',
    'Break Times': 'เวลาพัก',
    'Add Break': 'เพิ่มเวลาพัก',
    'At least 1 time period required': 'ต้องมีอย่างน้อย 1 ช่วงเวลา',
    'Weekly day off': 'วันหยุดประจำสัปดาห์',
    'Save Working Time': 'บันทึกเวลาทำงาน',
    'Saving...': 'กำลังบันทึก...',
    'Define work and break schedules': 'กำหนดเวลาทำงานและเวลาพักแยกตามรายวัน',
    'Alarm History': 'ประวัติแจ้งเตือน',
    'Show TRIGGER and RECOVERY events from PLC system': 'แสดงเหตุการณ์ TRIGGER และ RECOVERY จากระบบ PLC ทั้งหมด',
    'From date': 'จากวันที่',
    'To date': 'ถึงวันที่',
    'Threshold': 'ค่ากำหนด',
    'Actual Value': 'ค่าจริง',
    'Event Type': 'ประเภทเหตุการณ์',
    'Time Stamp': 'เวลาบันทึก',
    'Loading...': 'กำลังโหลดข้อมูล...',
    'View Chart': 'ดูกราฟ',
    'No alarm history found in selected date range': 'ไม่พบประวัติการแจ้งเตือนในช่วงวันที่เลือก',
    'to': 'ถึง',
    'Refresh Rate': 'อัตราการรีเฟรช',
    'Filter': 'ตัวกรอง',
    'Add Card': 'เพิ่มการ์ด',
    'Edit Card': 'แก้ไขการ์ด',
    'Save Changes': 'บันทึกการเปลี่ยนแปลง',
    'Insert Position': 'ตำแหน่งที่แทรก',
    'Add Element': 'เพิ่มองค์ประกอบ',
    'Select Layout': 'เลือกเลย์เอาต์',
    'Select a layout': 'เลือกเลย์เอาต์',
    'Edit Element': 'แก้ไของค์ประกอบ',
    'Add New Element': 'เพิ่มองค์ประกอบใหม่',
    'Element Type': 'ประเภทองค์ประกอบ',
    'Gauge Display': 'แสดงค่าเกจ',
    'Number Display': 'แสดงตัวเลข',
    'Status Lamp': 'ไฟสถานะ',
    'Control Button': 'ปุ่มควบคุม',
    'Level Progress Bar': 'แถบความคืบหน้า',
    'Position X': 'ตำแหน่ง X',
    'Position Y': 'ตำแหน่ง Y',
    'Size Width': 'ความกว้าง',
    'Size Height': 'ความสูง',
    'Precision': 'ความละเอียด',
    'Decimals': 'ทศนิยม',
    'Button Label': 'ข้อความปุ่ม',
    'Active Color': 'สีเมื่อทำงาน',
    'Inactive Color': 'สีเมื่อไม่ทำงาน',
    'Background Color': 'สีพื้นหลัง',
    'Text Color': 'สีตัวอักษร',
    'Bar Color': 'สีแถบ',
    'Font Size': 'ขนาดตัวอักษร',
    'Display Order': 'ลำดับการแสดง',
    'Visibility': 'การมองเห็น',
    'Visible': 'มองเห็นได้',
    'Clear': 'ล้าง',
    'Product Setting': 'ตั้งค่าผลิตภัณฑ์',
    'Add Product': 'เพิ่มผลิตภัณฑ์',
    'Edit Product': 'แก้ไขผลิตภัณฑ์',
    'Model Name': 'ชื่อรุ่น',
    'Image': 'รูปภาพ',
    'Enter Model Name': 'กรอกชื่อรุ่น',
    'No products found.': 'ไม่พบผลิตภัณฑ์',
    'Running': 'กำลังรัน',
    'PLC Address Configuration': 'การตั้งค่าที่อยู่ PLC',
    'PLC Address (ON/OFF)': 'ที่อยู่ PLC (เปิด/ปิด)',
    'e.g. D100, DB100.DBD0': 'ตัวอย่าง D100, DB100.DBD0',
    'Address for product ON/OFF signal': 'ที่อยู่สำหรับสัญญาณ เปิด/ปิด ของผลิตภัณฑ์',
    'PLC Address (Running)': 'ที่อยู่ PLC (กำลังทำงาน)',
    'e.g. M10, DB100.DBX0.0': 'ตัวอย่าง M10, DB100.DBX0.0',
    'Address for product running status': 'ที่อยู่สำหรับสถานะการทำงานของผลิตภัณฑ์',
    'Save PLC Addresses': 'บันทึกที่อยู่ PLC',
  },
  en: {
    'entries': 'entries',
    'Show': 'Show',
    'ประเภทอุปกรณ์': 'Device Type',
    'ประเภท': 'Type',
    'โหมดจำลอง': 'Demo / Simulate Mode',
    'โหมดจำลอง (สำรอง)': 'Simulate Mode',
    'เปิด': 'ON',
    'ปิด': 'OFF',
    'สุ่มทั้งหมด': 'Run Random All',
    'หยุดสุ่ม': 'Stop Random',
    'ค่า': 'Value',
    'ไม่พบอุปกรณ์': 'No devices found.',
    'แดชบอร์ด': 'Dashboard',
    'ตั้งค่า': 'Setting',
    'จำลอง': 'Demo',
    'ประวัติแจ้งเตือน': 'Alarm History',
    'ควบคุม': 'Interaction',
    'โหมดแก้ไข': 'Edit Mode',
    'ออกจากโหมดแก้ไข': 'Exit Edit',
    'เพิ่มการ์ด': 'Add Card',
    'ทุกห้อง': 'All Rooms',
    'ทุกประเภทอุปกรณ์': 'All Device Types',
    'การตั้งค่าระบบ': 'System Settings',
    'จัดการการตั้งค่าระบบ PLC Monitoring': 'Manage PLC system settings',
    'ตั้งค่าประเภทอุปกรณ์': 'Type Setting',
    'เพิ่มประเภท': 'Add Type',
    'ประเภทอุปกรณ์': 'Device Type',
    'จัดการ': 'Actions',
    'ไม่พบประเภทอุปกรณ์': 'No Device Types found.',
    'แก้ไขประเภทอุปกรณ์': 'Edit Device Type',
    'เพิ่มประเภทอุปกรณ์': 'Add Device Type',
    'ชื่อ': 'Name',
    'คำอธิบาย': 'Description',
    'ประเภทการแสดงผล': 'Display Types',
    'ยกเลิก': 'Cancel',
    'อัปเดต': 'Update',
    'สร้าง': 'Create',
    'แก้ไข': 'Edit',
    'ลบ': 'Delete',
    'บันทึก': 'Save',
    'ปิด': 'Close',
    'ค้นหา': 'Search',
    'เพิ่ม': 'Add',
    'เพิ่มอุปกรณ์': 'Add Device',
    'แก้ไขอุปกรณ์': 'Edit Device',
    'ที่อยู่': 'Address',
    'ป้ายชื่อ': 'Label',
    'ห้อง': 'Room',
    'ประเภท': 'Type',
    'ประเภทข้อมูล': 'Data Type',
    'ค่าต่ำสุด': 'Min',
    'ค่าสูงสุด': 'Max',
    'หน่วย': 'Unit',
    'แจ้งเตือน': 'Alert',
    'แจ้งเตือนต่ำ': 'Alert Low',
    'แจ้งเตือนสูง': 'Alert High',
    'ไม่มีอุปกรณ์': 'No devices.',
    'ช่วงเวลาทำงาน': 'Working Time',
    'เวลาเริ่มต้น': 'Start Time',
    'เวลาสิ้นสุด': 'End Time',
    'PLC Debug': 'PLC Debug',
    'ตั้งค่าห้อง': 'Room Setting',
    'เพิ่มห้อง': 'Add Room',
    'แก้ไขห้อง': 'Edit Room',
    'ไม่พบห้อง': 'No rooms found.',
    'อุปกรณ์': 'Device',
    'แสดง': 'Showing',
    'จาก': 'of',
    'รายการ': 'entries',
    'Device Type': 'Device Type',
    'Type': 'Type',
    'Work today': 'Work today',
    'Working Hours': 'Working Hours',
    'Add Shift': 'Add Shift',
    'Break Times': 'Break Times',
    'Add Break': 'Add Break',
    'At least 1 time period required': 'At least 1 time period required',
    'Weekly day off': 'Weekly day off',
    'Save Working Time': 'Save Working Time',
    'Saving...': 'Saving...',
    'Define work and break schedules': 'Define work and break schedules',
    'ประวัติแจ้งเตือน': 'Alarm History',
    'แสดงเหตุการณ์ TRIGGER และ RECOVERY จากระบบ PLC ทั้งหมด': 'Show TRIGGER and RECOVERY events from PLC system',
    'จากวันที่': 'From date',
    'ถึงวันที่': 'To date',
    'ค่ากำหนด': 'Threshold',
    'ค่าจริง': 'Actual Value',
    'ประเภทเหตุการณ์': 'Event Type',
    'เวลาบันทึก': 'Time Stamp',
    'กำลังโหลดข้อมูล...': 'Loading...',
    'ดูกราฟ': 'View Chart',
    'ไม่พบประวัติการแจ้งเตือนในช่วงวันที่เลือก': 'No alarm history found in selected date range',
    'ถึง': 'to',
    'อัตราการรีเฟรช': 'Refresh Rate',
    'ตัวกรอง': 'Filter',
    'เพิ่มการ์ด': 'Add Card',
    'แก้ไขการ์ด': 'Edit Card',
    'บันทึกการเปลี่ยนแปลง': 'Save Changes',
    'ตำแหน่งที่แทรก': 'Insert Position',
    'Edit Element': 'Edit Element',
    'Add New Element': 'Add New Element',
    'Element Type': 'Element Type',
    'Gauge Display': 'Gauge Display',
    'Number Display': 'Number Display',
    'Status Lamp': 'Status Lamp',
    'Control Button': 'Control Button',
    'Level Progress Bar': 'Level Progress Bar',
    'Position X': 'Position X',
    'Position Y': 'Position Y',
    'Size Width': 'Size Width',
    'Size Height': 'Size Height',
    'Precision': 'Precision',
    'Decimals': 'Decimals',
    'Button Label': 'Button Label',
    'Active Color': 'Active Color',
    'Inactive Color': 'Inactive Color',
    'Background Color': 'Background Color',
    'Text Color': 'Text Color',
    'Bar Color': 'Bar Color',
    'Font Size': 'Font Size',
    'Display Order': 'Display Order',
    'Visibility': 'Visibility',
    'Visible': 'Visible',
    'Clear': 'Clear',
    'Product Setting': 'Product Setting',
    'Add Product': 'Add Product',
    'Edit Product': 'Edit Product',
    'Model Name': 'Model Name',
    'Image': 'Image',
    'Enter Model Name': 'Enter Model Name',
    'No products found.': 'No products found.',
    'Running': 'Running',
    'การตั้งค่าที่อยู่ PLC': 'PLC Address Configuration',
    'ที่อยู่ PLC (เปิด/ปิด)': 'PLC Address (ON/OFF)',
    'ที่อยู่สำหรับสัญญาณ เปิด/ปิด ของผลิตภัณฑ์': 'Address for product ON/OFF signal',
    'ที่อยู่ PLC (กำลังทำงาน)': 'PLC Address (Running)',
    'ที่อยู่สำหรับสถานะการทำงานของผลิตภัณฑ์': 'Address for product running status',
    'บันทึกที่อยู่ PLC': 'Save PLC Addresses',
  }
};

const locale = reactive({
  current: 'th',
  t(key) {
    const dict = translations[this.current];
    return dict[key] || key;
  },
  toggle() {
    this.current = this.current === 'th' ? 'en' : 'th';
  }
});

app.provide('locale', locale);

app.mount("#app");

